redis-cli HSET M:Manage_vm:Forms 0 "yes:yes:ip:ip"
redis-cli HSET M:Manage_vm:Forms 1 "no:yes:mac:mac"
redis-cli HSET M:Manage_vm:Forms 2 "no:yes:hostname:host"
redis-cli HSET M:Manage_vm:Forms 3 "no:yes:Role:role"
redis-cli HSET M:Manage_vm:Forms 4 "no:no:Root password:pass"
redis-cli HSET M:Manage_vm:Forms 5 "no:yes:VMID:vmid"
redis-cli HSET M:Manage_vm:Forms 6 "no:yes:HyperViseur ID:hv_id"
redis-cli HSET M:Manage_vm:Select 0 "yes:Type HyperViseur:hv_type:Proxmox,ESXI"
redis-cli HSET M:Manage_vm:Select 1 "yes:Machine Type:type:VM,Physique"
redis-cli HSET M:Manage_vm:Select 2 "yes:Kernel:kernel:3.8,3.11"
redis-cli HSET M:Manage_vm:Button 0 "Blue:Start:Manage_vm_start_vm:#ip"
redis-cli HSET M:Manage_vm:Button 1 "Blue:Salt_it:Manage_vm_slat_accept_key:#host"
redis-cli RPUSH Shaker:module:list Manage_vm
