redis-cli HSET M:Network_Device:Forms 0 "yes:yes:id:id"
redis-cli HSET M:Network_Device:Forms 1 "no:yes:Device hostname/ip:hostname"
redis-cli HSET M:Network_Device:Forms 2 "no:yes:Interface:interface"
redis-cli HSET M:Network_Device:Forms 3 "no:yes:Vlans:vlans"
redis-cli HSET M:Network_Device:Forms 4 "no:yes:Description:description"
redis-cli HSET M:Network_Device:Select 0 "yes:VoIP:voip:oui,non"
redis-cli HSET M:Network_Device:Select 1 "yes:Active:active:on,off"
redis-cli HSET M:Network_Device:Button 0 "Red:Push:VLAN_CONF:#id?user,password"
redis-cli HSET M:Network_Device:Info alias "Network_Device"
redis-cli RPUSH Shaker:module:list Network_Device
